# Generated by Django 5.1.1 on 2024-09-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='main_ingredient',
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='category',
            field=models.ManyToManyField(to='recipe_app.category'),
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='main_ingredient',
            field=models.ManyToManyField(to='recipe_app.ingredient'),
        ),
    ]
